fallback_messages:
  - "Good morning! ğŸŒ Please share your progress, today's tasks, and any hurdles youâ€™re facing."
  - "Hey team! ğŸ¯ What did you achieve yesterday, whatâ€™s on your agenda today, and any blockers?"
  - "Rise and shine! â˜€ï¸ Update us on your progress, your focus for today, and any challenges."

slack:
  channel: "#slack-test-playground"

team_members:
  - "@Cindy Cuevas"
  - "@Firat Dogan"
  - "@Fabricio Gabriel"
  - "@Izabella Oliveira" 
  - "@Sasmit Mandloi"
